# Generated by Django 3.2.7 on 2021-10-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='src',
            field=models.URLField(default='/static/images/user-default.jpg'),
        ),
    ]
